version: '3.8'

networks:
  network:
    ipam:
      config:
        - subnet: 172.1.0.0/16
          
services: 
  timescaledb:
    image: timescale/timescaledb-ha:pg15-latest
    container_name: timescaledb
    ports:
      - "5432:5432"
    networks:
      network:
        ipv4_address: 172.1.0.10
    restart: always
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      PGDATA: '/pg-data'
      TZ: 'GMT+0'
      PGTZ: 'GMT+0'
    volumes:
      - ./data/timescale:/pg-data
      - ./data/import/:/import/
      - ./data/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  pgadmin4: 
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    networks:
      network:
        ipv4_address: 172.1.0.11
    environment:
      PGADMIN_DEFAULT_EMAIL: 'rileydavid@live.at'
      PGADMIN_DEFAULT_PASSWORD: 'password'
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
  

  # Does not work yet!
  # https://github.com/aganse/docker_mlflow_db/blob/main/mlflow/Dockerfile
  mlflow:
    build: ./mlflow
    image: mlflow_server
    container_name: mlflow_server
    restart: always
    ports:
      - "5000:5000"
    expose:
      - 5000
    networks:
      network:
        ipv4_address: 172.1.0.12
    #environment:
    #  - BACKEND=postgresql://admin:password@172.1.0.10:5432/mlflowdb
    #  - ARTIFACTS=/storage/mlruns  # in-container path to filestore in filesys
    volumes:
      - "./data/mlruns:/storage/mlruns"
    #  - "./data/condaenv:/opt/conda"
    #command: [
    #  "mlflow", "server", # something is not right here
    #  "--backend-store-uri", "postgresql://admin:password@172.1.0.10:5432/mlflowdb",
    #  "--default-artifact-root", "/storage/mlruns ",
    #  "--host", "0.0.0.0"
    #]
    #command: 
    #  - sh    # (sh allows for var substitution of BACKEND and ARTIFACTS)
    #  - -c
    #  - mlflow 
    #      --port 5000
    #      --host 0.0.0.0 
    #      --backend-store-uri $${BACKEND} 
    #      --default-artifact-root $${ARTIFACTS}

  backend: 
    build: ./backend_axum
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data/import/:/import/
    networks:
      network:
        ipv4_address: 172.1.0.14

  #grafana:
  #  image: grafana/grafana-oss
  #  container_name: grafana
  #  restart: unless-stopped
  #  ports:
  #    - '3000:3000'
  #  environment:
  #    GF_SECURITY_ADMIN_USER: 'admin'
  #    GF_SECURITY_ADMIN_PASSWORD: 'password' #default is admin/admin 
  #    GF_PATHS_CONFIG: '/etc/grafana/custom.ini'
  #  networks:
  #    network:
  #      ipv4_address: 172.1.0.12
  #  volumes: 
  #    - ./data/grafana:/var/lib/grafana
  #    - ./data/grafana/config/defaults.ini:/etc/grafana/custom.ini
  #  user: "472"
    
  #collector:
  #  build: ./collector
  #  container_name: collector
  #  restart: always
  #  networks:
  #    network:
  #      ipv4_address: 172.1.0.13

  #backend: 
  #  build: ./backend
  #  container_name: backend
  #  restart: always
  #  ports:
  #    - "8000:8000"
  #  networks:
  #    network:
  #      ipv4_address: 172.1.0.14

  #frontend: 
  #  build: ./frontend-angular
  #  container_name: frontend-angular
  #  restart: always
  #  ports:
  #    - "3000:80"
  #  networks:
  #    network:
  #      ipv4_address: 172.1.0.15

  #converter: 
  #  build: ./converter
  #  container_name: converter
  #  restart: no
  #  volumes:
  #    - ./data/:/data
  #  networks:
  #    network:
  #      ipv4_address: 172.1.0.99

