[package]
name = "webserver"
version = "0.1.0"
edition = "2021"

[dependencies]
# internal 
utils = { path = "../utils" }
service = {path = "../service"}
repository = { path = "../repository" }

# external
axum = { version = "0.6.2", features = ["headers", "macros", "multipart"] }
chrono = "0.4.23"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.23", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.4.4", features = ["cors"] }
validator = { version = "0.16", features = ["derive"] }
dotenvy = "0.15"
serde_with = "3.4.0"
tracing = "0.1"
jsonwebtoken = "9.1.0"
serde_json = "1.0"