[package]
name = "service"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
repository = { path = "../repository" }
cache = { path = "../cache" }

serde = "1.0.152"
chrono = {version = "0.4.31",features = ["serde"]}
tracing = "0.1.37"
openssl = { version = "0.10", features = ["vendored"] }
reqwest = { version = "0.11", features = ["json"] }
rayon = "1.8.0"


redis = "0.24.0"
rustis = {version = "0.12.4", features = ["redis-stack", "pool"]} 
sqlx = { version = "0.7.3", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid", "json"] }
