[package]
name = "repository"
version = "0.1.0"
edition = "2021"

[dependencies]
# internal
utils = { path = "../utils" }

# external
serde_json = "1.0.91"
sqlx = { version = "0.7.3", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid", "json", "bigdecimal"] }
tokio = { version = "1.24.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1.37"
chrono = { version = "0.4.23", features = ["serde"]}