[package]
name = "cache"
version = "0.1.0"
edition = "2021"

[dependencies]
# internal
utils = { path = "../utils" }
repository = { path = "../repository" }
#service = { path = "../service" }

# external
chrono = { version = "0.4.23", features = ["serde"]}
tracing = "0.1"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"]}
redis = "0.24.0"
rustis = {version = "0.12.4", features = ["redis-stack", "pool"]} 
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.106"