[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
# internal

# external
tokio = { version = "1.23", features = ["full"]}
sqlx = { version = "0.7.3", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid", "json"] }
axum = { version = "0.7.2", features = [ "macros"] } #"headers",
jsonwebtoken = "9.1.0"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"]}
chrono = "0.4"
async-trait = "0.1"
redis = "0.24.0"
rustis = {version = "0.12.4", features = ["redis-stack", "pool"]} 