[package]
name = "converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.30"
sqlx = { version = "0.7.2", features = [ "runtime-tokio-native-tls" , "postgres" , "bigdecimal", "chrono"] }
log = "0.4.20"
env_logger = "0.10.0"
threadpool = "1.8.1"
tokio = { version = "1.20", features = ["full"] } # full is probably overkill here
openssl = { version = "0.10", features = ["vendored"] }
dotenv = "0.15.0"
